# Generated by Django 2.0.5 on 2018-08-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeelist',
            name='cell',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='employeelist',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.Department'),
        ),
    ]
