# Generated by Django 2.0.5 on 2018-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20180802_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelist',
            name='message',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
